modLoader = "javafml"
loaderVersion = "[43,)" #This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "GPL-3.0"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "triavixlandorigins"
version = "1.0.3-unofficial-1.0"
displayName = "(Unofficial Fix) Triavixland Fantasy Origins"
refmapName="triavixlandorigins.refmap.json"

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "icon.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))

credits = "Original Triavixland Fantasy Origins by Triavixland (Trimipz), which is a fork of Medieval Origins Revival by MuonR (muon-rw)."
authors = "Triavixland (Trimipz); unofficial fix by Toirty" #optional
description = 'Unofficial fork of Triavixland Fantasy Origins to remove broken intoxicating_dagger reference.'

[[dependencies.triavixlandorigins]] #optional
modId = "forge"
mandatory = true
versionRange = "[47.1,)"
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.triavixlandorigins]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.triavixlandorigins]]
modId = "pehkui"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "BOTH"


